REGIONS = {
    "CAL": "California",
    "CAR": "Carolinas",
    "CENT": "Central",
    "FLA": "Florida",
    "MIDA": "Mid-Atlantic",
    "MIDW": "Midwest",
    "NE": "New England",
    "NW": "Northwest",
    "NY": "New York",
    "SE": "Southeast",
    "SW": "Southwest",
    "TEN": "Tennessee",
    "TEX": "Texas",
}

EASTERN = {
    code: name for code, name in REGIONS.items() if code in ["CAR", "FLA", "MIDA", "MIDW", "NE", "NY"]
}

CENTRAL = {
    code: name for code, name in REGIONS.items() if code in ["CENT", "SE", "TEN", "TEX", "NE", "NY"]
}

BAS = [
    "AECI",
    "AVA",
    "AZPS",
    "BANC",
    "BPAT",
    "CAL",
    "CAR",
    "CENT",
    "CHPD",
    "CISO",
    "CPLE",
    "CPLW",
    "DOPD",
    "DUK",
    "EPE",
    "ERCO",
    "FLA",
    "FMPP",
    "FPC",
    "FPL",
    "GCPD",
    "GVL",
    "HST",
    "IID",
    "IPCO",
    "ISNE",
    "JEA",
    "LDWP",
    "LGEE",
    "MIDA",
    "MIDW",
    "MISO",
    "NE",
    "NEVP",
    "NW",
    "NWMT",
    "NY",
    "NYIS",
    "PACE",
    "PACW",
    "PGE",
    "PJM",
    "PNM",
    "PSCO",
    "PSEI",
    "SC",
    "SCEG",
    "SCL",
    "SE",
    "SEC",
    "SOCO",
    "SPA",
    "SRP",
    "SW",
    "SWPP",
    "TAL",
    "TEC",
    "TEN",
    "TEPC",
    "TEX",
    "TIDC",
    "TPWR",
    "TVA",
    "US48",
    "WACM",
    "WALC",
    "WAUW",
]
