name: daily-demand-feature-pipeline

on:
  schedule:
   # run daily at midnight (UTC).
   - cron: '0 0 * * *'
  workflow_dispatch:

jobs:

  feature_pipeline:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Poetry
      uses: snok/install-poetry@v1

    # - name: Install hsfs
    #   run: poetry add "hsfs[python]"
    
    # - name: Install hopsworks
    #   run: poetry add hopsworks

    - name: Remove hopsworks and hsfs
      run: poetry remove hsfs hopsworks

    - name: Re-install hsfs
      run: poetry add "hsfs[python]"

    - name: Re-install hopsworks
      run: poetry add hopsworks
  
    - name: refresh dependencies
      run: poetry lock --no-update && poetry install

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

    - name: Execute python workflows from bash script
      working-directory: notebooks
      env:
        HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        EIA_API_KEY: ${{ secrets.EIA_API_KEY }}
      run: poetry run jupyter nbconvert --to notebook --execute 08_feature_pipeline.ipynb